.PHONY= doc clean

CC=g++
OPTIONS= -g 
DEBUG= #-D DEBUG
LIBDIR=lib
INCLUDEDIR=include
_OBJ= tporo.o tvectorporo.o tlistaporo.o tabbporo.o  tavlporo.o
OBJ = $(patsubst %,$(LIBDIR)/%,$(_OBJ))

tporo:    src//tporo/*.cpp $(OBJ)
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad01.cpp $(OBJ) -o Salida/tporo/tad01
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad02.cpp $(OBJ) -o Salida/tporo/tad02
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad03.cpp $(OBJ) -o Salida/tporo/tad03
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad04.cpp $(OBJ) -o Salida/tporo/tad04
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad05.cpp $(OBJ) -o Salida/tporo/tad05
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad06.cpp $(OBJ) -o Salida/tporo/tad06
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad07.cpp $(OBJ) -o Salida/tporo/tad07
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad08.cpp $(OBJ) -o Salida/tporo/tad08
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad09.cpp $(OBJ) -o Salida/tporo/tad09
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad10.cpp $(OBJ) -o Salida/tporo/tad10
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad11.cpp $(OBJ) -o Salida/tporo/tad11
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad12.cpp $(OBJ) -o Salida/tporo/tad12
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad13.cpp $(OBJ) -o Salida/tporo/tad13
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad14.cpp $(OBJ) -o Salida/tporo/tad14
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad15.cpp $(OBJ) -o Salida/tporo/tad15
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad16.cpp $(OBJ) -o Salida/tporo/tad16
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad17.cpp $(OBJ) -o Salida/tporo/tad17
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad18.cpp $(OBJ) -o Salida/tporo/tad18
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad19.cpp $(OBJ) -o Salida/tporo/tad19
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad20.cpp $(OBJ) -o Salida/tporo/tad20
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad21.cpp $(OBJ) -o Salida/tporo/tad21
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tporo/tad22.cpp $(OBJ) -o Salida/tporo/tad22

tvectorporo:    src/tvectorporo/*.cpp $(OBJ)
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad01.cpp $(OBJ) -o Salida/tvectorporo/tad01
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad02.cpp $(OBJ) -o Salida/tvectorporo/tad02
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad03.cpp $(OBJ) -o Salida/tvectorporo/tad03
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad04.cpp $(OBJ) -o Salida/tvectorporo/tad04
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad05.cpp $(OBJ) -o Salida/tvectorporo/tad05
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad06.cpp $(OBJ) -o Salida/tvectorporo/tad06
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad07.cpp $(OBJ) -o Salida/tvectorporo/tad07
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad08.cpp $(OBJ) -o Salida/tvectorporo/tad08
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad09.cpp $(OBJ) -o Salida/tvectorporo/tad09
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad10.cpp $(OBJ) -o Salida/tvectorporo/tad10
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad11.cpp $(OBJ) -o Salida/tvectorporo/tad11
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad12.cpp $(OBJ) -o Salida/tvectorporo/tad12
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad13.cpp $(OBJ) -o Salida/tvectorporo/tad13
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad14.cpp $(OBJ) -o Salida/tvectorporo/tad14
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad15.cpp $(OBJ) -o Salida/tvectorporo/tad15
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad16.cpp $(OBJ) -o Salida/tvectorporo/tad16
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad17.cpp $(OBJ) -o Salida/tvectorporo/tad17
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad18.cpp $(OBJ) -o Salida/tvectorporo/tad18
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad19.cpp $(OBJ) -o Salida/tvectorporo/tad19
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad20.cpp $(OBJ) -o Salida/tvectorporo/tad20
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad21.cpp $(OBJ) -o Salida/tvectorporo/tad21
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tvectorporo/tad22.cpp $(OBJ) -o Salida/tvectorporo/tad22

tlistaporo:    src/tlistaporo/*.cpp $(OBJ)
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad01.cpp $(OBJ) -o Salida/tlistaporo/tad01
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad02.cpp $(OBJ) -o Salida/tlistaporo/tad02
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad03.cpp $(OBJ) -o Salida/tlistaporo/tad03
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad04.cpp $(OBJ) -o Salida/tlistaporo/tad04
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad05.cpp $(OBJ) -o Salida/tlistaporo/tad05
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad06.cpp $(OBJ) -o Salida/tlistaporo/tad06
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad07.cpp $(OBJ) -o Salida/tlistaporo/tad07
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad08.cpp $(OBJ) -o Salida/tlistaporo/tad08
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad09.cpp $(OBJ) -o Salida/tlistaporo/tad09
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad10.cpp $(OBJ) -o Salida/tlistaporo/tad10
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad11.cpp $(OBJ) -o Salida/tlistaporo/tad11
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad12.cpp $(OBJ) -o Salida/tlistaporo/tad12
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad13.cpp $(OBJ) -o Salida/tlistaporo/tad13
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad14.cpp $(OBJ) -o Salida/tlistaporo/tad14
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad15.cpp $(OBJ) -o Salida/tlistaporo/tad15
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad16.cpp $(OBJ) -o Salida/tlistaporo/tad16
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad17.cpp $(OBJ) -o Salida/tlistaporo/tad17
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tlistaporo/tad18.cpp $(OBJ) -o Salida/tlistaporo/tad18

tabbporo: 	src/tabbporo/*.cpp $(OBJ)
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-01.cpp $(OBJ) -o Salida/tabbporo/TABBPoro01
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-02.cpp $(OBJ) -o Salida/tabbporo/TABBPoro02
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-03.cpp $(OBJ) -o Salida/tabbporo/TABBPoro03
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-04.cpp $(OBJ) -o Salida/tabbporo/TABBPoro04
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-05.cpp $(OBJ) -o Salida/tabbporo/TABBPoro05
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-06.cpp $(OBJ) -o Salida/tabbporo/TABBPoro06
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-07.cpp $(OBJ) -o Salida/tabbporo/TABBPoro07
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-08.cpp $(OBJ) -o Salida/tabbporo/TABBPoro08
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-09.cpp $(OBJ) -o Salida/tabbporo/TABBPoro09
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-10.cpp $(OBJ) -o Salida/tabbporo/TABBPoro10
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-11.cpp $(OBJ) -o Salida/tabbporo/TABBPoro11
	#$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tabbporo/TABBPoro-12.cpp $(OBJ) -o Salida/tabbporo/TABBPoro12

tavlporo: 	src/tavlporo/*.cpp $(OBJ)
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad01.cpp $(OBJ) -o Salida/tavlporo/tad01
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad02.cpp $(OBJ) -o Salida/tavlporo/tad02
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad03.cpp $(OBJ) -o Salida/tavlporo/tad03
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad04.cpp $(OBJ) -o Salida/tavlporo/tad04
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad05.cpp $(OBJ) -o Salida/tavlporo/tad05
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad06.cpp $(OBJ) -o Salida/tavlporo/tad06
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad07.cpp $(OBJ) -o Salida/tavlporo/tad07
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad08.cpp $(OBJ) -o Salida/tavlporo/tad08
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad09.cpp $(OBJ) -o Salida/tavlporo/tad09
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad10.cpp $(OBJ) -o Salida/tavlporo/tad10
	$(CC) $(OPTIONS) $(DEBUG) -I$(INCLUDEDIR) src/tavlporo/tad11.cpp $(OBJ) -o Salida/tavlporo/tad11


$(LIBDIR)/%.o : $(LIBDIR)/%.cpp $(INCLUDEDIR)/%.h
	$(CC) $(OPTIONS) $(DEBUG) -c -I$(INCLUDEDIR) -o $@ $<
	
doc:
	doxygen

clean:
	rm -f $(OBJ) && rm Salida/tlistaporo/* && rm Salida/tabbporo/* && rm Salida/tvectorporo/* && rm Salida/tporo/* && rm Salida/tavlporo/*